name: API Quality Gates

on:
  push:
    branches:
      - master
      - develop
      - release/**
    paths:
      - api/**/*
      - .github/workflows/api-quality-gates.yml
  pull_request:
    branches:
      - master
      - develop
      - release/**
    paths:
      - api/**/*
      - .github/workflows/api-quality-gates.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Restore dotnet tools
      run: dotnet tool restore
      working-directory: ./api

    - name: Install dependencies
      run: dotnet restore
      working-directory: ./api

    - name: Build
      run: dotnet build -c Release --no-restore
      working-directory: ./api

    - name: Run unit tests
      run: dotnet test -c Release --no-build -v normal
      working-directory: ./api/tests/api.unitTests

    - name: Run integration tests
      run: dotnet test -c Release --no-build -v normal
      working-directory: ./api/tests/api.integrationTests
      env:
        APEX_Sql__UseSqliteForTesting: true
